/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_end = 1,
  anon_sym_theory = 2,
  anon_sym_imports = 3,
  anon_sym_begin = 4,
  anon_sym_lemma = 5,
  anon_sym_COLON = 6,
  anon_sym_theorem = 7,
  anon_sym_definition = 8,
  anon_sym_COLON_COLON = 9,
  anon_sym_where = 10,
  anon_sym_datatype = 11,
  anon_sym_EQ = 12,
  anon_sym_PIPE = 13,
  anon_sym_proof = 14,
  anon_sym_qed = 15,
  anon_sym_apply = 16,
  anon_sym_done = 17,
  anon_sym_by = 18,
  anon_sym_sorry = 19,
  anon_sym_assume = 20,
  anon_sym_have = 21,
  anon_sym_show = 22,
  anon_sym_LPAREN = 23,
  anon_sym_RPAREN = 24,
  sym_inner_syntax = 25,
  anon_sym_LPAREN_STAR = 26,
  aux_sym_comment_token1 = 27,
  anon_sym_DASH_DASH = 28,
  aux_sym_comment_token2 = 29,
  sym_identifier = 30,
  sym_source_file = 31,
  sym_theory_definition = 32,
  sym__command = 33,
  sym_lemma_command = 34,
  sym_theorem_command = 35,
  sym_definition_command = 36,
  sym_datatype_command = 37,
  sym__datatype_constructors = 38,
  sym_proof = 39,
  sym__proof_step = 40,
  sym_method = 41,
  sym_comment = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_theory_definition_repeat1 = 44,
  aux_sym__datatype_constructors_repeat1 = 45,
  aux_sym_proof_repeat1 = 46,
  aux_sym_proof_repeat2 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_end] = "end",
  [anon_sym_theory] = "theory",
  [anon_sym_imports] = "imports",
  [anon_sym_begin] = "begin",
  [anon_sym_lemma] = "lemma",
  [anon_sym_COLON] = ":",
  [anon_sym_theorem] = "theorem",
  [anon_sym_definition] = "definition",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_where] = "where",
  [anon_sym_datatype] = "datatype",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [anon_sym_proof] = "proof",
  [anon_sym_qed] = "qed",
  [anon_sym_apply] = "apply",
  [anon_sym_done] = "done",
  [anon_sym_by] = "by",
  [anon_sym_sorry] = "sorry",
  [anon_sym_assume] = "assume",
  [anon_sym_have] = "have",
  [anon_sym_show] = "show",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_inner_syntax] = "inner_syntax",
  [anon_sym_LPAREN_STAR] = "(*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_DASH_DASH] = "--",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_theory_definition] = "theory_definition",
  [sym__command] = "_command",
  [sym_lemma_command] = "lemma_command",
  [sym_theorem_command] = "theorem_command",
  [sym_definition_command] = "definition_command",
  [sym_datatype_command] = "datatype_command",
  [sym__datatype_constructors] = "_datatype_constructors",
  [sym_proof] = "proof",
  [sym__proof_step] = "_proof_step",
  [sym_method] = "method",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_theory_definition_repeat1] = "theory_definition_repeat1",
  [aux_sym__datatype_constructors_repeat1] = "_datatype_constructors_repeat1",
  [aux_sym_proof_repeat1] = "proof_repeat1",
  [aux_sym_proof_repeat2] = "proof_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_theory] = anon_sym_theory,
  [anon_sym_imports] = anon_sym_imports,
  [anon_sym_begin] = anon_sym_begin,
  [anon_sym_lemma] = anon_sym_lemma,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_theorem] = anon_sym_theorem,
  [anon_sym_definition] = anon_sym_definition,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_datatype] = anon_sym_datatype,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_proof] = anon_sym_proof,
  [anon_sym_qed] = anon_sym_qed,
  [anon_sym_apply] = anon_sym_apply,
  [anon_sym_done] = anon_sym_done,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_sorry] = anon_sym_sorry,
  [anon_sym_assume] = anon_sym_assume,
  [anon_sym_have] = anon_sym_have,
  [anon_sym_show] = anon_sym_show,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_inner_syntax] = sym_inner_syntax,
  [anon_sym_LPAREN_STAR] = anon_sym_LPAREN_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_theory_definition] = sym_theory_definition,
  [sym__command] = sym__command,
  [sym_lemma_command] = sym_lemma_command,
  [sym_theorem_command] = sym_theorem_command,
  [sym_definition_command] = sym_definition_command,
  [sym_datatype_command] = sym_datatype_command,
  [sym__datatype_constructors] = sym__datatype_constructors,
  [sym_proof] = sym_proof,
  [sym__proof_step] = sym__proof_step,
  [sym_method] = sym_method,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_theory_definition_repeat1] = aux_sym_theory_definition_repeat1,
  [aux_sym__datatype_constructors_repeat1] = aux_sym__datatype_constructors_repeat1,
  [aux_sym_proof_repeat1] = aux_sym_proof_repeat1,
  [aux_sym_proof_repeat2] = aux_sym_proof_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theory] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_imports] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_begin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lemma] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theorem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_definition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datatype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_proof] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_qed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_apply] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_done] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sorry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assume] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_have] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_show] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_inner_syntax] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_theory_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym_lemma_command] = {
    .visible = true,
    .named = true,
  },
  [sym_theorem_command] = {
    .visible = true,
    .named = true,
  },
  [sym_definition_command] = {
    .visible = true,
    .named = true,
  },
  [sym_datatype_command] = {
    .visible = true,
    .named = true,
  },
  [sym__datatype_constructors] = {
    .visible = false,
    .named = true,
  },
  [sym_proof] = {
    .visible = true,
    .named = true,
  },
  [sym__proof_step] = {
    .visible = false,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_theory_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__datatype_constructors_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_proof_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_proof_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(79);
      ADVANCE_MAP(
        '"', 3,
        '(', 110,
        ')', 111,
        '-', 11,
        ':', 87,
        '=', 94,
        'a', 57,
        'b', 19,
        'd', 13,
        'e', 46,
        'h', 14,
        'i', 42,
        'l', 25,
        'p', 61,
        'q', 26,
        's', 33,
        't', 34,
        'w', 35,
        '|', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(110);
      if (lookahead == '-') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'w') ADVANCE(134);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(112);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(110);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'a') ADVANCE(140);
      if (lookahead == 'h') ADVANCE(124);
      if (lookahead == 'q') ADVANCE(126);
      if (lookahead == 's') ADVANCE(133);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == 'b') ADVANCE(131);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == '*') ADVANCE(116);
      if (lookahead == '-') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(113);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(116);
      if (lookahead == '-') ADVANCE(118);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(116);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(114);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(117);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(90);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(69);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(80);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(97);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'y') ADVANCE(102);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(41);
      if (lookahead == 'y') ADVANCE(81);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'f') ADVANCE(96);
      END_STATE();
    case 31:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(51);
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(29);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(27);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(88);
      END_STATE();
    case 42:
      if (lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 44:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 45:
      if (lookahead == 'm') ADVANCE(23);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 53:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 57:
      if (lookahead == 'p') ADVANCE(58);
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 58:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 59:
      if (lookahead == 'p') ADVANCE(55);
      END_STATE();
    case 60:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 65:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 67:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 68:
      if (lookahead == 's') ADVANCE(82);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 73:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 74:
      if (lookahead == 'v') ADVANCE(21);
      END_STATE();
    case 75:
      if (lookahead == 'w') ADVANCE(108);
      END_STATE();
    case 76:
      if (lookahead == 'y') ADVANCE(99);
      END_STATE();
    case 77:
      if (lookahead == 'y') ADVANCE(103);
      END_STATE();
    case 78:
      if (lookahead == 'y') ADVANCE(60);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_theory);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_imports);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_begin);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_begin);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_lemma);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_theorem);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_definition);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_where);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_datatype);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_proof);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_qed);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_qed);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_apply);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_apply);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_done);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_by);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_sorry);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_assume);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_assume);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_have);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_have);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_show);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_show);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(113);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_inner_syntax);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead == '*') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '*') ADVANCE(9);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(123);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '*') ADVANCE(9);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead == '*') ADVANCE(116);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(123);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '(') ADVANCE(121);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(123);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(123);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '-') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(123);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(145);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(98);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(125);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(107);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(105);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(142);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(135);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(139);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(129);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(138);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(147);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(128);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(84);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(146);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(141);
      if (lookahead == 's') ADVANCE(143);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(136);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(130);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(144);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(137);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(127);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(109);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(100);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 120},
  [87] = {.lex_state = 4},
  [88] = {(TSStateId)(-1),},
  [89] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_theory] = ACTIONS(1),
    [anon_sym_imports] = ACTIONS(1),
    [anon_sym_begin] = ACTIONS(1),
    [anon_sym_lemma] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_theorem] = ACTIONS(1),
    [anon_sym_definition] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_datatype] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_proof] = ACTIONS(1),
    [anon_sym_qed] = ACTIONS(1),
    [anon_sym_apply] = ACTIONS(1),
    [anon_sym_done] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_sorry] = ACTIONS(1),
    [anon_sym_assume] = ACTIONS(1),
    [anon_sym_have] = ACTIONS(1),
    [anon_sym_show] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_inner_syntax] = ACTIONS(1),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
    [anon_sym_DASH_DASH] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym_theory_definition] = STATE(2),
    [sym_comment] = STATE(1),
    [anon_sym_theory] = ACTIONS(7),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
    [anon_sym_DASH_DASH] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_end,
    ACTIONS(11), 1,
      anon_sym_lemma,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(15), 1,
      anon_sym_definition,
    ACTIONS(17), 1,
      anon_sym_datatype,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__command,
    STATE(34), 4,
      sym_lemma_command,
      sym_theorem_command,
      sym_definition_command,
      sym_datatype_command,
  [37] = 11,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(11), 1,
      anon_sym_lemma,
    ACTIONS(13), 1,
      anon_sym_theorem,
    ACTIONS(15), 1,
      anon_sym_definition,
    ACTIONS(17), 1,
      anon_sym_datatype,
    ACTIONS(19), 1,
      anon_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__command,
    STATE(34), 4,
      sym_lemma_command,
      sym_theorem_command,
      sym_definition_command,
      sym_datatype_command,
  [74] = 10,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(21), 1,
      anon_sym_end,
    ACTIONS(23), 1,
      anon_sym_lemma,
    ACTIONS(26), 1,
      anon_sym_theorem,
    ACTIONS(29), 1,
      anon_sym_definition,
    ACTIONS(32), 1,
      anon_sym_datatype,
    STATE(31), 1,
      sym__command,
    STATE(4), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(34), 4,
      sym_lemma_command,
      sym_theorem_command,
      sym_definition_command,
      sym_datatype_command,
  [109] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(5), 1,
      sym_comment,
    ACTIONS(35), 11,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
      anon_sym_qed,
      anon_sym_apply,
      anon_sym_done,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [132] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(6), 1,
      sym_comment,
    ACTIONS(37), 11,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
      anon_sym_qed,
      anon_sym_apply,
      anon_sym_done,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [155] = 11,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(39), 1,
      anon_sym_qed,
    ACTIONS(41), 1,
      anon_sym_apply,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_identifier,
    STATE(7), 1,
      sym_comment,
    STATE(10), 1,
      sym_method,
    STATE(11), 1,
      aux_sym_proof_repeat1,
    STATE(25), 1,
      sym__proof_step,
    ACTIONS(43), 3,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [191] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(49), 1,
      anon_sym_proof,
    ACTIONS(51), 1,
      anon_sym_apply,
    ACTIONS(55), 1,
      anon_sym_by,
    STATE(8), 1,
      sym_comment,
    STATE(21), 1,
      sym_proof,
    STATE(43), 1,
      aux_sym_proof_repeat2,
    ACTIONS(53), 2,
      anon_sym_done,
      anon_sym_sorry,
  [220] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(49), 1,
      anon_sym_proof,
    ACTIONS(51), 1,
      anon_sym_apply,
    ACTIONS(55), 1,
      anon_sym_by,
    STATE(9), 1,
      sym_comment,
    STATE(38), 1,
      sym_proof,
    STATE(43), 1,
      aux_sym_proof_repeat2,
    ACTIONS(53), 2,
      anon_sym_done,
      anon_sym_sorry,
  [249] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(57), 1,
      anon_sym_qed,
    ACTIONS(59), 1,
      anon_sym_apply,
    STATE(10), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_proof_repeat1,
    STATE(25), 1,
      sym__proof_step,
    ACTIONS(61), 3,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [276] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(57), 1,
      anon_sym_qed,
    ACTIONS(59), 1,
      anon_sym_apply,
    STATE(11), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_proof_repeat1,
    STATE(25), 1,
      sym__proof_step,
    ACTIONS(61), 3,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [303] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(49), 1,
      anon_sym_proof,
    ACTIONS(51), 1,
      anon_sym_apply,
    ACTIONS(55), 1,
      anon_sym_by,
    STATE(12), 1,
      sym_comment,
    STATE(32), 1,
      sym_proof,
    STATE(43), 1,
      aux_sym_proof_repeat2,
    ACTIONS(53), 2,
      anon_sym_done,
      anon_sym_sorry,
  [332] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(63), 1,
      anon_sym_qed,
    ACTIONS(65), 1,
      anon_sym_apply,
    STATE(25), 1,
      sym__proof_step,
    STATE(13), 2,
      sym_comment,
      aux_sym_proof_repeat1,
    ACTIONS(68), 3,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [357] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(49), 1,
      anon_sym_proof,
    ACTIONS(51), 1,
      anon_sym_apply,
    ACTIONS(55), 1,
      anon_sym_by,
    STATE(14), 1,
      sym_comment,
    STATE(20), 1,
      sym_proof,
    STATE(43), 1,
      aux_sym_proof_repeat2,
    ACTIONS(53), 2,
      anon_sym_done,
      anon_sym_sorry,
  [386] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(59), 1,
      anon_sym_apply,
    ACTIONS(71), 1,
      anon_sym_qed,
    STATE(13), 1,
      aux_sym_proof_repeat1,
    STATE(15), 1,
      sym_comment,
    STATE(25), 1,
      sym__proof_step,
    ACTIONS(61), 3,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [413] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(75), 1,
      anon_sym_PIPE,
    STATE(16), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym__datatype_constructors_repeat1,
    ACTIONS(73), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [436] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(75), 1,
      anon_sym_PIPE,
    STATE(16), 1,
      aux_sym__datatype_constructors_repeat1,
    STATE(17), 1,
      sym_comment,
    ACTIONS(77), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [459] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(81), 1,
      anon_sym_PIPE,
    STATE(18), 2,
      sym_comment,
      aux_sym__datatype_constructors_repeat1,
    ACTIONS(79), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [480] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(79), 6,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
      anon_sym_PIPE,
  [498] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(84), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [515] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(86), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [532] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(88), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [549] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(90), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [566] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(92), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [583] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(94), 5,
      anon_sym_qed,
      anon_sym_apply,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [600] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(96), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [617] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [634] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(100), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [651] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(102), 5,
      anon_sym_qed,
      anon_sym_apply,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [668] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(104), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [685] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(106), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [702] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(108), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [719] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(110), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [736] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(112), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [753] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(114), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [770] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(116), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [787] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(118), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [804] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(120), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [821] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(39), 1,
      sym_comment,
    ACTIONS(122), 5,
      anon_sym_qed,
      anon_sym_apply,
      anon_sym_assume,
      anon_sym_have,
      anon_sym_show,
  [838] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(124), 5,
      anon_sym_end,
      anon_sym_lemma,
      anon_sym_theorem,
      anon_sym_definition,
      anon_sym_datatype,
  [855] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(126), 1,
      anon_sym_COLON_COLON,
    ACTIONS(128), 1,
      anon_sym_where,
    ACTIONS(130), 1,
      sym_inner_syntax,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(41), 1,
      sym_comment,
  [877] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(134), 1,
      anon_sym_COLON,
    ACTIONS(136), 1,
      anon_sym_COLON_COLON,
    ACTIONS(138), 1,
      anon_sym_where,
    ACTIONS(140), 1,
      sym_inner_syntax,
    STATE(42), 1,
      sym_comment,
  [899] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(51), 1,
      anon_sym_apply,
    ACTIONS(142), 1,
      anon_sym_done,
    STATE(43), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_proof_repeat2,
  [918] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(144), 1,
      anon_sym_COLON_COLON,
    ACTIONS(146), 1,
      anon_sym_where,
    ACTIONS(148), 1,
      sym_inner_syntax,
    STATE(44), 1,
      sym_comment,
  [937] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(150), 1,
      anon_sym_apply,
    ACTIONS(153), 1,
      anon_sym_done,
    STATE(45), 2,
      sym_comment,
      aux_sym_proof_repeat2,
  [954] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(46), 1,
      sym_comment,
    STATE(54), 1,
      sym_method,
  [973] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(157), 1,
      anon_sym_begin,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(47), 2,
      sym_comment,
      aux_sym_theory_definition_repeat1,
  [990] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(162), 1,
      anon_sym_begin,
    ACTIONS(164), 1,
      sym_identifier,
    STATE(47), 1,
      aux_sym_theory_definition_repeat1,
    STATE(48), 1,
      sym_comment,
  [1009] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(24), 1,
      sym_method,
    STATE(49), 1,
      sym_comment,
  [1028] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(29), 1,
      sym_method,
    STATE(50), 1,
      sym_comment,
  [1047] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_begin,
      sym_identifier,
  [1061] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(28), 1,
      sym__datatype_constructors,
    STATE(52), 1,
      sym_comment,
  [1077] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(170), 1,
      anon_sym_where,
    ACTIONS(172), 1,
      sym_inner_syntax,
    STATE(53), 1,
      sym_comment,
  [1093] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_apply,
      anon_sym_done,
  [1107] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(48), 1,
      aux_sym_theory_definition_repeat1,
    STATE(55), 1,
      sym_comment,
  [1123] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(146), 1,
      anon_sym_where,
    ACTIONS(148), 1,
      sym_inner_syntax,
    STATE(56), 1,
      sym_comment,
  [1139] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(176), 1,
      sym_inner_syntax,
    ACTIONS(178), 1,
      sym_identifier,
    STATE(57), 1,
      sym_comment,
  [1155] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(180), 1,
      sym_inner_syntax,
    ACTIONS(182), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
  [1171] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(184), 1,
      anon_sym_where,
    ACTIONS(186), 1,
      sym_inner_syntax,
    STATE(59), 1,
      sym_comment,
  [1187] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(188), 1,
      sym_inner_syntax,
    ACTIONS(190), 1,
      sym_identifier,
    STATE(60), 1,
      sym_comment,
  [1203] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(192), 1,
      sym_inner_syntax,
    STATE(61), 1,
      sym_comment,
  [1216] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(186), 1,
      sym_inner_syntax,
    STATE(62), 1,
      sym_comment,
  [1229] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(194), 1,
      sym_inner_syntax,
    STATE(63), 1,
      sym_comment,
  [1242] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(196), 1,
      sym_inner_syntax,
    STATE(64), 1,
      sym_comment,
  [1255] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(198), 1,
      sym_inner_syntax,
    STATE(65), 1,
      sym_comment,
  [1268] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(140), 1,
      sym_inner_syntax,
    STATE(66), 1,
      sym_comment,
  [1281] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(200), 1,
      sym_identifier,
    STATE(67), 1,
      sym_comment,
  [1294] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(202), 1,
      sym_inner_syntax,
    STATE(68), 1,
      sym_comment,
  [1307] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(204), 1,
      anon_sym_COLON,
    STATE(69), 1,
      sym_comment,
  [1320] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_comment,
  [1333] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(148), 1,
      sym_inner_syntax,
    STATE(71), 1,
      sym_comment,
  [1346] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      sym_comment,
  [1359] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(210), 1,
      anon_sym_EQ,
    STATE(73), 1,
      sym_comment,
  [1372] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      sym_comment,
  [1385] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(214), 1,
      sym_identifier,
    STATE(75), 1,
      sym_comment,
  [1398] = 4,
    ACTIONS(216), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(218), 1,
      aux_sym_comment_token1,
    ACTIONS(220), 1,
      anon_sym_DASH_DASH,
    STATE(76), 1,
      sym_comment,
  [1411] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym_comment,
  [1424] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(172), 1,
      sym_inner_syntax,
    STATE(78), 1,
      sym_comment,
  [1437] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(79), 1,
      sym_comment,
  [1450] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(226), 1,
      sym_identifier,
    STATE(80), 1,
      sym_comment,
  [1463] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(228), 1,
      sym_inner_syntax,
    STATE(81), 1,
      sym_comment,
  [1476] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(230), 1,
      anon_sym_imports,
    STATE(82), 1,
      sym_comment,
  [1489] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
    STATE(83), 1,
      sym_comment,
  [1502] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(234), 1,
      anon_sym_COLON,
    STATE(84), 1,
      sym_comment,
  [1515] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(236), 1,
      sym_inner_syntax,
    STATE(85), 1,
      sym_comment,
  [1528] = 4,
    ACTIONS(216), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(220), 1,
      anon_sym_DASH_DASH,
    ACTIONS(238), 1,
      aux_sym_comment_token2,
    STATE(86), 1,
      sym_comment,
  [1541] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH,
    ACTIONS(240), 1,
      anon_sym_COLON,
    STATE(87), 1,
      sym_comment,
  [1554] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1558] = 1,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 109,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 155,
  [SMALL_STATE(8)] = 191,
  [SMALL_STATE(9)] = 220,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 276,
  [SMALL_STATE(12)] = 303,
  [SMALL_STATE(13)] = 332,
  [SMALL_STATE(14)] = 357,
  [SMALL_STATE(15)] = 386,
  [SMALL_STATE(16)] = 413,
  [SMALL_STATE(17)] = 436,
  [SMALL_STATE(18)] = 459,
  [SMALL_STATE(19)] = 480,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 515,
  [SMALL_STATE(22)] = 532,
  [SMALL_STATE(23)] = 549,
  [SMALL_STATE(24)] = 566,
  [SMALL_STATE(25)] = 583,
  [SMALL_STATE(26)] = 600,
  [SMALL_STATE(27)] = 617,
  [SMALL_STATE(28)] = 634,
  [SMALL_STATE(29)] = 651,
  [SMALL_STATE(30)] = 668,
  [SMALL_STATE(31)] = 685,
  [SMALL_STATE(32)] = 702,
  [SMALL_STATE(33)] = 719,
  [SMALL_STATE(34)] = 736,
  [SMALL_STATE(35)] = 753,
  [SMALL_STATE(36)] = 770,
  [SMALL_STATE(37)] = 787,
  [SMALL_STATE(38)] = 804,
  [SMALL_STATE(39)] = 821,
  [SMALL_STATE(40)] = 838,
  [SMALL_STATE(41)] = 855,
  [SMALL_STATE(42)] = 877,
  [SMALL_STATE(43)] = 899,
  [SMALL_STATE(44)] = 918,
  [SMALL_STATE(45)] = 937,
  [SMALL_STATE(46)] = 954,
  [SMALL_STATE(47)] = 973,
  [SMALL_STATE(48)] = 990,
  [SMALL_STATE(49)] = 1009,
  [SMALL_STATE(50)] = 1028,
  [SMALL_STATE(51)] = 1047,
  [SMALL_STATE(52)] = 1061,
  [SMALL_STATE(53)] = 1077,
  [SMALL_STATE(54)] = 1093,
  [SMALL_STATE(55)] = 1107,
  [SMALL_STATE(56)] = 1123,
  [SMALL_STATE(57)] = 1139,
  [SMALL_STATE(58)] = 1155,
  [SMALL_STATE(59)] = 1171,
  [SMALL_STATE(60)] = 1187,
  [SMALL_STATE(61)] = 1203,
  [SMALL_STATE(62)] = 1216,
  [SMALL_STATE(63)] = 1229,
  [SMALL_STATE(64)] = 1242,
  [SMALL_STATE(65)] = 1255,
  [SMALL_STATE(66)] = 1268,
  [SMALL_STATE(67)] = 1281,
  [SMALL_STATE(68)] = 1294,
  [SMALL_STATE(69)] = 1307,
  [SMALL_STATE(70)] = 1320,
  [SMALL_STATE(71)] = 1333,
  [SMALL_STATE(72)] = 1346,
  [SMALL_STATE(73)] = 1359,
  [SMALL_STATE(74)] = 1372,
  [SMALL_STATE(75)] = 1385,
  [SMALL_STATE(76)] = 1398,
  [SMALL_STATE(77)] = 1411,
  [SMALL_STATE(78)] = 1424,
  [SMALL_STATE(79)] = 1437,
  [SMALL_STATE(80)] = 1450,
  [SMALL_STATE(81)] = 1463,
  [SMALL_STATE(82)] = 1476,
  [SMALL_STATE(83)] = 1489,
  [SMALL_STATE(84)] = 1502,
  [SMALL_STATE(85)] = 1515,
  [SMALL_STATE(86)] = 1528,
  [SMALL_STATE(87)] = 1541,
  [SMALL_STATE(88)] = 1554,
  [SMALL_STATE(89)] = 1558,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proof_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proof_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proof_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__datatype_constructors, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__datatype_constructors, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__datatype_constructors_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__datatype_constructors_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_command, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_command, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_command, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theory_definition, 5, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proof, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proof_repeat1, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_command, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_command, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datatype_command, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__proof_step, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proof, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lemma_command, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_command, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proof, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proof, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_command, 6, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lemma_command, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__proof_step, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_command, 7, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proof_repeat2, 2, 0, 0), SHIFT_REPEAT(46),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proof_repeat2, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_theory_definition_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_theory_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_theory_definition_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [208] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_isabelle(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
